version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: zoo1
        hostname: zoo1
        volumes: 
            - "./datas/zk1:/root/zookeeper/data"
        networks:
            hadoop:
                aliases:
                    - zoo1
        tty: true

    zoo2:
        image: zookeeper
        restart: always
        container_name: zoo2
        hostname: zoo2
        volumes: 
            - "./datas/zk2:/root/zookeeper/data"
        networks:
            hadoop:
                aliases:
                    - zoo2
        tty: true
        
    zoo3:
        image: zookeeper
        restart: always
        container_name: zoo3
        hostname: zoo3
        volumes: 
            - "./datas/zk3:/root/zookeeper/data"
        networks:
            hadoop:
                aliases:
                    - zoo3
        tty: true
        
networks:
    hadoop:
        external:
            name: hadoop