version: '2'
services:
    hadoop-master:
        image: hadoop
        container_name: hadoop-master
        ports:
            - "50070:50070"
            - "8088:8088"
        volumes:
            - "./work:/root/works"
        hostname: hadoop-master
        networks:
            - hadoop
        tty: true
     
    hadoop-slave1:
        image: hadoop
        container_name: hadoop-slave1
        volumes: 
            - "/root/work:/root/works"
        hostname: hadoop-slave1
        networks:
            - hadoop
        tty: true
    
    hadoop-slave2:
        image: hadoop
        container_name: hadoop-slave2
        volumes: 
            - "/root/work:/root/works"
        hostname: hadoop-slave2
        networks:
            - hadoop
        tty: true
        
    hadoop-slave3:
        image: hadoop
        container_name: hadoop-slave3
        volumes: 
            - "/root/work:/root/works"
        hostname: hadoop-slave3
        networks:
            - hadoop
        tty: true

networks:
    hadoop:
        external:
            name: hadoop